server:
  port: 10085

#TODO
spring:
  datasource:
    url: jdbc:mysql://124.71.101.139:3306/recruitment-platform-data?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
#    username: recruitment-platform-data
#    password: mysoftwareproject
    username: wjm
    password: wjm123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
#  type-aliases-package: com.platform.ats.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: deleteFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.platform.ats: debug